# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8aba3e225d9f5408e622c74483ee739910851d2e53e1d147d6dd194bf2b404f3bbe7aea70d196a3e79d4d681e451414df016821e47371889d668938caf1184c7

test:
  secret_key_base: 8138cd153c6fec9502f4da8b027e52f78022bfc9769252a27d067bb9c329b1a4aab663e8c068e1a02da6f35bf82597d94b12b02aa1ee13bdc48602afd909f683

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
